name: Run Tests

on:
  pull_request:
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Enable Corepack
      run: corepack enable

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'
    
    - name: Install Aztec CLI
      run: |
        curl -s https://install.aztec.network | bash
        export PATH="$PATH:/home/runner/.aztec/bin"
        aztec-up 3.0.0-devnet.6-patch.1
        echo "/home/runner/.aztec/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Setup Foundry
      uses: foundry-rs/foundry-toolchain@v1

    # - name: Run EVM tests
    #   run: cd packages/evm && forge test

    - name: Run Aztec gateway tests
      run: |
        cd packages/aztec/aztec_gateway_7683
        yarn compile
        yarn codegen
        yarn test

    - name: Run filler tests
      run: |
        cd packages/filler
        yarn build
        export EVM_L2_CHAIN_ID=84532
        export FORWARDER_CHAIN_ID=11155111
        export BEACON_API_URL=https://eth-sepoliabeacon.g.alchemy.com/v2/xxxx
        export EVM_L2_RPC_URL=https://sepolia.base.org
        export AZTEC_RPC_URL=https://devnet-6.aztec-labs.com/
        export AZTEC_PROVER_ENABLED=true
        export FORWARDER_RPC_URL=https://ethereum-sepolia-rpc.publicnode.com
        export MONGO_DB_URI=mongodb://localhost:27018
        export MONGO_DB_NAME=filler
        export MONGO_DB_USER=xxx
        export MONGO_DB_PASSWORD=xxx
        export MONGO_DB_AUTH_SOURCE=xxx
        export MONGO_PORT=27017
        export EVM_WATCH_INTERVAL_TIME_MS=5000
        export AZTEC_WATCH_INTERVAL_TIME_MS=5000
        export DEPLOYMENT_JSON_PATH=../../deployments/deploy_2026-01-29_16-47-42.json
        export TOKENS_JSON_PATH=../../deployments/tokens_deploy_2026-01-29_16-49-15.json
        export OP_STACK_ANCHOR_REGISTRY_ADDRESS=0x0729957c92A1F50590A84cb2D65D761093f3f8eB
        export AZTEC_ROLLUP_CONTRACT_L1_ADDRESS=0x5d84b64b0b2f468df065d8cf01fff88a73238a13
        export AZTEC_SANDBOX=false
        export PK_EVM=0xBEEF
        export AZTEC_SECRET_KEY=0xBEEF
        export AZTEC_SALT=0xBEEF
        yarn test

    - name: Run SDK tests
      run: |
        cd packages/sdk
        yarn build
        yarn playwright install --with-deps chromium
        yarn test:unit